# Generated by Django 4.2.16 on 2024-11-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
    ]
